/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Blog: () => import('#controllers/blog_controller'),
  Tips: () => import('#controllers/tips_controller'),
  WellKnown: () => import('#controllers/well_known_controller'),
}
